export const cars = [
  {
    id: '1',
    name: 'Nissan GT-R',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/nissan_gtr/nissan_gtr_PNG37.png',
    pricePerDay: 99,
    fuel: '90L',
    transmission: 'Manual',
    capacity: 2,
  },
  {
    id: '2',
    name: 'BMW M4',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/bmw/bmw_PNG99534.png',
    pricePerDay: 85,
    fuel: '75L',
    transmission: 'Manual',
    capacity: 4,
  },
  {
    id: '3',
    name: 'Audi R8',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/audi/audi_PNG1760.png',
    pricePerDay: 95,
    fuel: '73L',
    transmission: 'Automatic',
    capacity: 2,
  },
  {
    id: '4',
    name: 'Mercedes S-Class',
    type: 'Luxury',
    image: 'https://pngimg.com/uploads/mercedes/mercedes_PNG80171.png',
    pricePerDay: 110,
    fuel: '85L',
    transmission: 'Automatic',
    capacity: 5,
  },
  {
    id: '5',
    name: 'Lamborghini Aventador',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/lamborghini/lamborghini_PNG10709.png',
    pricePerDay: 150,
    fuel: '90L',
    transmission: 'Manual',
    capacity: 2,
  },
  {
    id: '16',
    name: 'Porsche 911',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/porsche/porsche_PNG102820.png',
    pricePerDay: 130,
    fuel: '70L',
    transmission: 'Automatic',
    capacity: 2,
  },
  {
    id: '17',
    name: 'McLaren 720S',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/mclaren/mclaren_PNG27.png',
    pricePerDay: 180,
    fuel: '72L',
    transmission: 'Manual',
    capacity: 2,
  },
  {
    id: '18',
    name: 'Bugatti Chiron',
    type: 'Hypercar',
    image: 'https://pngimg.com/uploads/bugatti/bugatti_PNG22.png',
    pricePerDay: 300,
    fuel: '100L',
    transmission: 'Automatic',
    capacity: 2,
  },
  {
    id: '19',
    name: 'Toyota Supra',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/toyota/toyota_PNG1925.png',
    pricePerDay: 85,
    fuel: '65L',
    transmission: 'Manual',
    capacity: 2,
  },
  {
    id: '20',
    name: 'Mazda MX-5',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/mazda/mazda_PNG86.png',
    pricePerDay: 60,
    fuel: '50L',
    transmission: 'Manual',
    capacity: 2,
  },
  {
    id: '21',
    name: 'Chevrolet Corvette',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/chevrolet/chevrolet_PNG154.png',
    pricePerDay: 95,
    fuel: '70L',
    transmission: 'Manual',
    capacity: 2,
  },
  {
    id: '22',
    name: 'Ford GT',
    type: 'Supercar',
    image: 'https://pngimg.com/uploads/ford/ford_PNG122.png',
    pricePerDay: 210,
    fuel: '80L',
    transmission: 'Manual',
    capacity: 2,
  },
  {
    id: '23',
    name: 'Hyundai Elantra',
    type: 'Sedan',
    image: 'https://pngimg.com/uploads/hyundai/hyundai_PNG112.png',
    pricePerDay: 45,
    fuel: '55L',
    transmission: 'Automatic',
    capacity: 5,
  },
  {
    id: '25',
    name: 'Volvo XC90',
    type: 'SUV',
    image: 'https://pngimg.com/uploads/volvo/volvo_PNG71.png',
    pricePerDay: 95,
    fuel: '85L',
    transmission: 'Automatic',
    capacity: 7,
  },
  {
    id: '26',
    name: 'Land Cruiser',
    type: 'SUV',
    image: 'https://pngimg.com/uploads/toyota/toyota_PNG1942.png',
    pricePerDay: 110,
    fuel: '90L',
    transmission: 'Automatic',
    capacity: 7,
  },
  {
    id: '27',
    name: 'Mini Cooper',
    type: 'Hatchback',
    image: 'https://pngimg.com/uploads/mini/mini_PNG120.png',
    pricePerDay: 55,
    fuel: '45L',
    transmission: 'Manual',
    capacity: 4,
  },
  {
    id: '28',
    name: 'Volkswagen Golf',
    type: 'Hatchback',
    image: 'https://pngimg.com/uploads/volkswagen/volkswagen_PNG178.png',
    pricePerDay: 58,
    fuel: '50L',
    transmission: 'Manual',
    capacity: 5,
  },
  {
    id: '29',
    name: 'Peugeot 508',
    type: 'Sedan',
    image: 'https://pngimg.com/uploads/peugeot/peugeot_PNG34.png',
    pricePerDay: 52,
    fuel: '60L',
    transmission: 'Automatic',
    capacity: 5,
  },
  {
    id: '30',
    name: 'Skoda Octavia',
    type: 'Sedan',
    image: 'https://pngimg.com/uploads/skoda/skoda_PNG71.png',
    pricePerDay: 50,
    fuel: '60L',
    transmission: 'Automatic',
    capacity: 5,
  },
  {
    id: '31',
    name: 'Subaru WRX',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/subaru/subaru_PNG47.png',
    pricePerDay: 82,
    fuel: '65L',
    transmission: 'Manual',
    capacity: 4,
  },
  {
    id: '32',
    name: 'Dodge Charger',
    type: 'Muscle',
    image: 'https://pngimg.com/uploads/dodge/dodge_PNG136.png',
    pricePerDay: 88,
    fuel: '72L',
    transmission: 'Automatic',
    capacity: 5,
  },
  {
    id: '33',
    name: 'Tesla Model X',
    type: 'Electric',
    image: 'https://pngimg.com/uploads/tesla/tesla_PNG44.png',
    pricePerDay: 120,
    fuel: 'Electric',
    transmission: 'Automatic',
    capacity: 7,
  },
  {
    id: '34',
    name: 'Tesla Model 3',
    type: 'Electric',
    image: 'https://pngimg.com/uploads/tesla/tesla_PNG39.png',
    pricePerDay: 85,
    fuel: 'Electric',
    transmission: 'Automatic',
    capacity: 5,
  },
  {
    id: '35',
    name: 'Range Rover Sport',
    type: 'SUV',
    image: 'https://pngimg.com/uploads/land_rover/land_rover_PNG58.png',
    pricePerDay: 140,
    fuel: '90L',
    transmission: 'Automatic',
    capacity: 5,
  },
];
