import { Car } from '@/types/car';

export const mockCars: Car[] = [
  {
    id: '1',
    name: 'Nissan GT-R',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/nissan_gtr/nissan_gtr_PNG37.png',
    pricePerDay: 99,
    fuel: '90L',
    transmission: 'Manual',
    capacity: 2,
  },
  {
    id: '2',
    name: 'BMW M4',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/bmw/bmw_PNG99534.png',
    pricePerDay: 85,
    fuel: '75L',
    transmission: 'Manual',
    capacity: 4,
  },
  {
    id: '3',
    name: 'Audi R8',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/audi/audi_PNG1760.png',
    pricePerDay: 95,
    fuel: '73L',
    transmission: 'Automatic',
    capacity: 2,
  },
  {
    id: '4',
    name: 'Mercedes S-Class',
    type: 'Luxury',
    image: 'https://pngimg.com/uploads/mercedes/mercedes_PNG80171.png',
    pricePerDay: 110,
    fuel: '85L',
    transmission: 'Automatic',
    capacity: 5,
  },
  {
    id: '5',
    name: 'Lamborghini Aventador',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/lamborghini/lamborghini_PNG10709.png',
    pricePerDay: 150,
    fuel: '90L',
    transmission: 'Manual',
    capacity: 2,
  },
  {
    id: '16',
    name: 'Porsche 911',
    type: 'Sport',
    image: 'https://pngimg.com/uploads/porsche/porsche_PNG102820.png',
    pricePerDay: 130,
    fuel: '70L',
    transmission: 'Automatic',
    capacity: 2,
  },
  {
   id: '17',
    name: 'McLaren 720S',
  type: 'Sport',
   image: 'https://pngimg.com/uploads/mclaren/mclaren_PNG27.png',
   pricePerDay: 180,
   fuel: '72L',
    transmission: 'Manual',
   capacity: 2,
  },
  {
    id: '18',
    name: 'Bugatti Chiron',
    type: 'Hypercar',
    image: 'https://pngimg.com/uploads/bugatti/bugatti_PNG22.png',
    pricePerDay: 300,
    fuel: '100L',
    transmission: 'Automatic',
    capacity: 2,
  },
  
  
  
];
